---
title: "Mesocarnivore community temporal analyses: regressions for MARTEN" ## name of your project
author: "Julie Louvrier, Aimara Planillo, Stephanie Kramer-Schadt"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
    code_folding: hide                  ## hide or show code by default?
    toc_depth: 3                        ## 3-level TOC
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:do urban mesocarnivores experience temporal partitioning in gardens? **
* **Study area: Berlin fall 2018, spring 2019, fall 2019, spring 2020, fall 2020**
* **Data: all seasons detection histories** 


# Setup
### Packages

```{r packages}
rm(list=ls())
## for non-CRAN packages please keep install instruction
## but commented so it is not run each time, e.g.
# devtools::install_github("EcoDynIZW/template")

# libraries used in this script
# please add ALL LIBRARIES NEEDED HERE
# please remove libraries from the list that are not needed anymore
# at a later stage
### load required libraries ####
package.list=c("bayestestR",
               "camtrapR",
               "car",
               "dplyr",
               "evaluate",
               "gdata",
               "ggplot2",
               "here",
               "janitor",
               "insight",
               "maptools",
               "MASS",
               "optimbase",
               "plyr",
               "raster",
               "readxl",
               #"rgdal",
               #"rgeos",
               #"rjags",
               "rlecuyer",
               "rstanarm",
               "showtext",
               #"sf",
               "sjlabelled",
               "sjmisc",
               "sjPlot",
               "snowfall",
               #"sp",
               "stringr",
               "tidyverse"
               )



for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
```

### Workspace
```{r}
WorkDir <- here::here()


procdata_wd <- file.path(WorkDir, "output/data-proc/temporal_processed_data")
plots_wd <- file.path(WorkDir, "plots/temp")
```

### Loading data
```{r}

cat_mart <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_cat_marten_id_covenv2021_10_28.RDS"))

rac_mart <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_raccoon_marten_id_covenv2021_10_28.RDS"))

mart_mart <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_marten_marten_id_covenv2021_10_28.RDS"))

fox_mart <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_fox_marten_id_covenv2021_10_28.RDS"))
```

# Data prep
## all gardens

```{r}
#adding the species column
fox_mart_species <- cbind(fox_mart, species = "fox")
cat_mart_species <- cbind(cat_mart, species = "cat")
rac_mart_species <- cbind(rac_mart, species = "raccoon")
mart_mart_species <- cbind(mart_mart, species = "marten")

#rbinding everything
delta_mart <- rbind(mart_mart_species,
                   fox_mart_species,
                   cat_mart_species,
                   rac_mart_species)

delta_mart$species <- factor(delta_mart$species, levels = c("marten", "fox","cat", "raccoon"))

#transforming to positive means
delta_mart$mean <- - (delta_mart$mean)
delta_mart <- delta_mart[-(which(delta_mart$mean==0)),] #taking out the zeros because it doesn't work

#scaling all the other variables
#first,renaming
names(delta_mart) <- c("User_uid","value","season","garden_type",
                      "garden_size","Local_tree_cover","fence_height","compost","Lat", "Long",
                      "pop_100","dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border",
                      "inside","species")

#scaling the values
delta_mart[,c("garden_size","Local_tree_cover","fence_height","pop_100",
              "dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border")] <- scale(delta_mart[,c("garden_size","Local_tree_cover","fence_height","pop_100", "dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border")])

#setting the season as factor
delta_mart$season <- as.factor((delta_mart$season))


```

# running model
```{r}
#adding a new covid column
delta_mart_covid = delta_mart %>% mutate(covid = factor(ifelse(season == "1"| season == "2"| season == "3", "0", "1")))


#replacing the seasons by fall and spring
delta_mart_covid_season_binary = delta_mart_covid %>% mutate(season_binary = factor(ifelse(season == "2"| season == "4", "spring", "fall")))

saveRDS(delta_mart_covid_season_binary,file = here::here("output", "data-proc", "temporal_processed_data", paste0("delta_mart_covid_season_binary",gsub("-", "_", Sys.Date()),".RDS")))


# make sure we apply a nice theme
theme_set(theme_sjplot())


#### with stan ####
m_mart_12_covid <- stan_glmer(value ~ (1 | User_uid) + garden_size + Local_tree_cover + fence_height +
                        pop_100 + imperv_100 + noise_100 + tree_cover_100 + distance_border + season_binary + covid+ compost + species, 
                       family = Gamma,data = delta_mart_covid_season_binary, chains = 2, prior_intercept = normal(0,1), 
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_mart_12_covid) + ylim(.85, 1.2)

describe_posterior(m_mart_12_covid, test = c("p_direction","rope","bayesfactor"))

saveRDS(m_mart_12_covid, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_mart_12_covid",gsub("-", "_", Sys.Date()),".RDS")))


```

## Now checking the results, running some post predictive checks

```{r}
m_mart_12_covid <- readRDS(here::here("output", "data-proc", "temporal_processed_data", paste0("m_mart_12_covid2021_10_29",".RDS")))


describe_posterior(m_mart_12_covid, test = c("p_direction","rope","bayesfactor"))

pp_check(m_mart_12_covid)
ppcheckMart_line <- pp_check(m_mart_12_covid) + xlim(c(0,12)) +
                      ggtitle("Marten") 
ggsave(plot = ppcheckMart_line, paste0(plots_wd, "/ppcheckMart_line", gsub("-", "_", Sys.Date()),".png"), height=8, width=9, units='in', dpi=600)

```


#run separately for each species couple 

```{r}
###marten fox 
#marten marten
delta_mart_mart_only <- delta_mart_covid_season_binary %>% filter(species == "marten")

#marten fox
delta_mart_fox_only <- delta_mart_covid_season_binary %>% filter(species == "fox")

#selecting the gardens where both species are present
garden_mart_fox_ID <- Reduce(intersect, list(delta_mart_mart_only$User_uid,                          delta_mart_fox_only$User_uid))

#selecting the data
mart_mart_only <- delta_mart_mart_only[which(delta_mart_mart_only$User_uid %in% garden_mart_fox_ID),]
fox_mart_only <- delta_mart_fox_only[which(delta_mart_fox_only$User_uid %in% garden_mart_fox_ID),]

#putting them all together
delta_mart_fox <- rbind(mart_mart_only, fox_mart_only)


m_mart_2species_fox <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_mart_fox, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_mart_2species_fox) + ylim(.85, 1.2)

describe_posterior(m_mart_2species_fox, test = c("p_direction","rope","bayesfactor"))


##marten raccoon
#marten raccoon
delta_mart_raccoon_only <- delta_mart_covid_season_binary %>% filter(species == "raccoon")

#selecting the gardens where both species are present
garden_mart_raccoon_ID <- Reduce(intersect, list(delta_mart_mart_only$User_uid,                          delta_mart_raccoon_only$User_uid))

#selecting the data
mart_mart_only <- delta_mart_mart_only[which(delta_mart_mart_only$User_uid %in% garden_mart_raccoon_ID),]
raccoon_mart_only <- delta_mart_raccoon_only[which(delta_mart_raccoon_only$User_uid %in% garden_mart_raccoon_ID),]

#putting them all together
delta_mart_raccoon <- rbind(mart_mart_only, raccoon_mart_only)


m_mart_2species_raccoon <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_mart_raccoon, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_mart_2species_raccoon) + ylim(.85, 1.2)

describe_posterior(m_mart_2species_raccoon, test = c("p_direction","rope","bayesfactor"))


##marten cat
#marten cat
delta_mart_cat_only <- delta_mart_covid_season_binary %>% filter(species == "cat")

#selecting the gardens where both species are present
garden_mart_cat_ID <- Reduce(intersect, list(delta_mart_mart_only$User_uid,                          delta_mart_cat_only$User_uid))

#selecting the data
mart_mart_only <- delta_mart_mart_only[which(delta_mart_mart_only$User_uid %in% garden_mart_cat_ID),]
cat_mart_only <- delta_mart_cat_only[which(delta_mart_cat_only$User_uid %in% garden_mart_cat_ID),]

#putting them all together
delta_mart_cat <- rbind(mart_mart_only, cat_mart_only)


m_mart_2species_cat <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_mart_cat, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_mart_2species_cat) + ylim(.85, 1.2)

describe_posterior(m_mart_2species_cat, test = c("p_direction","rope","bayesfactor"))

saveRDS(m_mart_2species_fox, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_mart_2species_fox",gsub("-", "_", Sys.Date()),".RDS")))

saveRDS(m_mart_2species_raccoon, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_mart_2species_raccoon",gsub("-", "_", Sys.Date()),".RDS")))

saveRDS(m_mart_2species_cat, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_mart_2species_cat",gsub("-", "_", Sys.Date()),".RDS")))



```

