---
title: "Mesocarnivore community temporal analyses: regressions for FOX" ## name of your project
author: "Julie Louvrier, Aimara Planillo, Stephanie Kramer-Schadt"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
    code_folding: hide                  ## hide or show code by default?
    toc_depth: 3                        ## 3-level TOC
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:do urban mesocarnivores experience temporal partitioning in gardens? **
* **Study area: Berlin fall 2018, spring 2019, fall 2019, spring 2020, fall 2020**
* **Data: all seasons detection histories** 


# Setup
### Packages

```{r packages}
rm(list=ls())
## for non-CRAN packages please keep install instruction
## but commented so it is not run each time, e.g.
# devtools::install_github("EcoDynIZW/template")

## libraries used in this script
## please add ALL LIBRARIES NEEDED HERE
## please remove libraries from the list that are not needed anymore 
## at a later stage
#### load required libraries ####
package.list=c("bayestestR",
               "camtrapR",
               "car",
               "dplyr",
               "evaluate",
               "gdata",
               "ggplot2",
               "here",
               "janitor",
               "insight",
               "maptools",
               "MASS",
               "optimbase",
               "plyr",
               "raster",
               "readxl",
               #"rgdal",
               #"rgeos",
               #"rjags",
               "rlecuyer",
               "rstanarm",
               "showtext",
               #"sf",
               "sjlabelled",
               "sjmisc",
               "sjPlot",
               "snowfall",
               #"sp",
               "stringr",
               "tidyverse"
               )



for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}
```

### Workspace
```{r}
WorkDir <- here::here()


procdata_wd <- file.path(WorkDir, "output/data-proc/temporal_processed_data")
plots_wd <- file.path(WorkDir, "plots/temp")
```

### Loading data
```{r}

cat_fox <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_cat_fox_id_covenv2021_10_28.RDS"))

rac_fox <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_raccoon_fox_id_covenv2021_10_28.RDS"))

mart_fox <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_marten_fox_id_covenv2021_10_28.RDS"))

fox_fox <- readRDS(here::here("output", "data-proc", "temporal_processed_data", "average_diff_fox_fox_id_covenv2021_10_28.RDS"))


```

# data prep

```{r}
#adding the species column
fox_fox_species <- cbind(fox_fox, species = "fox")
cat_fox_species <- cbind(cat_fox, species = "cat")
rac_fox_species <- cbind(rac_fox, species = "raccoon")
mart_fox_species <- cbind(mart_fox, species = "marten")


#rbinding everything
delta_fox <- rbind(fox_fox_species,
                   cat_fox_species,
                   rac_fox_species,
                   mart_fox_species)


delta_fox$species <- factor(delta_fox$species, levels = c("fox", "cat", "raccoon","marten"))

#transforming to positive values
delta_fox$mean <- - (delta_fox$mean)
delta_fox <- delta_fox[-(which(delta_fox$mean==0)),] #taking out the zeros because it doesn't work

#scaling all the other variables
#first,renaming
names(delta_fox) <- c("User_uid","value","season","garden_type",
                      "garden_size","Local_tree_cover","fence_height","compost","Lat", "Long",
                      "pop_100","dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border",
                      "inside","species")

#scaling the values
delta_fox[,c("garden_size","Local_tree_cover","fence_height","pop_100",
                         "dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border")] <- scale(delta_fox[,c("garden_size","Local_tree_cover","fence_height","pop_100",
                                                                                                                                      "dist_water_100", "imperv_100", "noise_100", "tree_cover_100", "distance_border")])


#setting the season as factor
delta_fox$season <- as.factor((delta_fox$season))

```

# running model
```{r}
delta_fox$season

#adding a new covid column
delta_fox_covid = delta_fox %>% mutate(covid = factor(ifelse(season == "1"| season == "2"| season == "3", "0", "1")))


#replacing the seasons by fall and spring
delta_fox_covid_season_binary = delta_fox_covid %>% mutate(season_binary = factor(ifelse(season == "2"| season == "4", "spring", "fall")))

saveRDS(delta_fox_covid_season_binary,file = here::here("output", "data-proc", "temporal_processed_data", paste0("delta_fox_covid_season_binary",gsub("-", "_", Sys.Date()),".RDS")))


# make sure we apply a nice theme
theme_set(theme_sjplot())


#### with stan ####
m_fox_12_covid <- stan_glmer(value ~ (1 | User_uid) + garden_size + Local_tree_cover + fence_height +
                        pop_100 + imperv_100 + noise_100 + tree_cover_100 + distance_border + season_binary + covid+ compost + species, 
                       family = Gamma,data = delta_fox_covid_season_binary, chains = 2, prior_intercept = normal(0,1), 
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_fox_12_covid) + ylim(.85, 1.2)


describe_posterior(m_fox_12_covid, test = c("p_direction","rope","bayesfactor"))

saveRDS(m_fox_12_covid, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_12_covid",gsub("-", "_", Sys.Date()),".RDS")))

saveRDS(m_fox_12_covid, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_12_covid",gsub("-", "_", Sys.Date()),".RDS")))

```


#Now checking the results, running some post predictive checks

```{r}
m_fox_12_covid <- readRDS(here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_12_covid2021_10_29",".RDS")))


describe_posterior(m_fox_12_covid, test = c("p_direction","rope","bayesfactor"))

ppcheckFox_line <- pp_check(m_fox_12_covid) +
                    xlim(c(0,12)) +
                    ggtitle("Fox") 

ggsave(plot = ppcheckFox_line, paste0(plots_wd, "/ppcheckFox_line", gsub("-", "_", Sys.Date()),".png"), height=8, width=9, units='in', dpi=600)

```


#run separately for each species couple 

```{r}
####fox marten 
#fox fox
delta_fox_fox_only <- delta_fox_covid_season_binary %>% filter(species == "fox")

#fox marten
delta_fox_mart_only <- delta_fox_covid_season_binary %>% filter(species == "marten")

#selecting the gardens where both species are present
garden_fox_marten_ID <- Reduce(intersect, list(delta_fox_fox_only$User_uid,                          delta_fox_mart_only$User_uid))

#selecting the data
fox_fox_only <- delta_fox_fox_only[which(delta_fox_fox_only$User_uid %in% garden_fox_marten_ID),]
fox_marten_only <- delta_fox_mart_only[which(delta_fox_mart_only$User_uid %in% garden_fox_marten_ID),]

#putting them all together
delta_fox_mart <- rbind(fox_fox_only, fox_marten_only)


m_fox_2species_mart <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_fox_mart, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_fox_2species_fox) + ylim(.85, 1.2)

describe_posterior(m_fox_2species_mart, test = c("p_direction","rope","bayesfactor"))


##fox raccoon
#fox raccoon
delta_fox_raccoon_only <- delta_fox_covid_season_binary %>% filter(species == "raccoon")

#selecting the gardens where both species are present
garden_fox_raccoon_ID <- Reduce(intersect, list(delta_fox_fox_only$User_uid,                          delta_fox_raccoon_only$User_uid))

#selecting the data
fox_fox_only <- delta_fox_fox_only[which(delta_fox_fox_only$User_uid %in% garden_fox_raccoon_ID),]
raccoon_fox_only <- delta_fox_raccoon_only[which(delta_fox_raccoon_only$User_uid %in% garden_fox_raccoon_ID),]

#putting them all together
delta_fox_raccoon <- rbind(fox_fox_only, raccoon_fox_only)


m_fox_2species_raccoon <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_fox_raccoon, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_fox_2species_raccoon) + ylim(.85, 1.2)

describe_posterior(m_fox_2species_raccoon, test = c("p_direction","rope","bayesfactor"))


##fox cat
#fox cat
delta_fox_cat_only <- delta_fox_covid_season_binary %>% filter(species == "cat")

#selecting the gardens where both species are present
garden_fox_cat_ID <- Reduce(intersect, list(delta_fox_fox_only$User_uid,                          delta_fox_cat_only$User_uid))

#selecting the data
fox_fox_only <- delta_fox_fox_only[which(delta_fox_fox_only$User_uid %in% garden_fox_cat_ID),]
cat_fox_only <- delta_fox_cat_only[which(delta_fox_cat_only$User_uid %in% garden_fox_cat_ID),]

#putting them all together
delta_fox_cat <- rbind(fox_fox_only, cat_fox_only)


m_fox_2species_cat <- stan_glmer(value ~ (1 | User_uid) + species,
                       family = Gamma,data = delta_fox_cat, chains = 2, prior_intercept = normal(0,1),
                       prior = normal(0,1), seed = 12345, iter=3000, warmup=1000)

#plot_model(m_fox_2species_cat) + ylim(.85, 1.2)

describe_posterior(m_fox_2species_cat, test = c("p_direction","rope","bayesfactor"))

saveRDS(m_fox_2species_mart, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_2species_mart",gsub("-", "_", Sys.Date()),".RDS")))

saveRDS(m_fox_2species_raccoon, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_2species_rac",gsub("-", "_", Sys.Date()),".RDS")))

saveRDS(m_fox_2species_cat, file = here::here("output", "data-proc", "temporal_processed_data", paste0("m_fox_2species_cat",gsub("-", "_", Sys.Date()),".RDS")))


```


